### ISSUE TITLE
Requires 2.0 nightlies to install from nimble

### ISSUE THREAD

**Issue by SpiderDave** [Angluca/tigr-nim#1]
The latest version of Nim I use is 1.6.13, and when installing tigr I get 
```undeclared identifier: 'taskRequires'```

It does work with 1.9.1 (2.0 branch) but I don't use that due to compatibility issues.

**Comment by Angluca** [comment]
Only example/opengl/ogl.nim want nimble install opengl
I use 1.9.1devel so don't know 1.6.13 haven't taskRequires 
I fix it
