### ISSUE TITLE
Collision with Tiger Package in Nimble Install

### ISSUE THREAD

**Issue by foxoman** [Angluca/tigr-nim#3]
While attempting to install the "tiger" package using Nimble, a collision occurs with the existing "tiger" package found in https://git.sr.ht/~ehmry/nim_tiger/tree/master/item/src/tiger.nim. As a result, it may be beneficial to rename the package to "ntiger" or a similar name to prevent future collisions.

```
nimble install tiger
Downloading https://git.sr.ht/~ehmry/nim_tiger using git
  Verifying dependencies for tiger@0.2.1
 Installing tiger@0.2.1
  Success:  tiger installed successfully.
```

**Comment by Angluca** [comment]
This is tigr not tiger :)

**Comment by foxoman** [comment]
osh :) keep dreaming od tigers
