### ISSUE TITLE
demo.nim fails to compile with Nim 1.6.10

### ISSUE THREAD

**Issue by FedericoCeratto** [Angluca/tigr-nim#4]
`nim r examples/hello/hello.nim` fails with:

```
src/tigr.nim(356, 60) Error: type mismatch: got <char>
but expected one of:
proc `addr`[T](x: var T): ptr T
  first type mismatch at position: 1
  required type for x: var T
  but expression 'sz[0]' is immutable, not 'var'
```

Is tigr Nim 2.0 only?
By the way, probably the `requires "nim >= 0.20.0"` line in the nimble file should be changed.

**Comment by Angluca** [comment]
En...  nim >= 1.9.1

**Comment by FedericoCeratto** [comment]
Thanks for the update. Any hope it can support Nim 1.6.10 perhaps?

**Comment by Angluca** [comment]
Can support , But must change code, 
You can commet tigr.nim bottom (356 line) converter functions,  you can test
I will sleep now, Maybe I try change to support 1.6.x at Afternoon.
In fact, the earlier versions support 1.6.x

**Comment by Angluca** [comment]
Maybe nim >= 1.6 support now, You can try it

**Comment by FedericoCeratto** [comment]
@Angluca it works, thank you!
